// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovementIntel.Domain;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MovementIntel.Domain.Migrations
{
    [DbContext(typeof(MovementIntelDbContext))]
    partial class MovementIntelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MovementIntel.Domain.Entities.EntityHourlyStats", b =>
                {
                    b.Property<string>("EntityType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entity_type");

                    b.Property<string>("EntityId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_id");

                    b.Property<DateTime>("BucketHour")
                        .HasColumnType("timestamptz")
                        .HasColumnName("bucket_hour");

                    b.Property<int>("EventCount")
                        .HasColumnType("integer")
                        .HasColumnName("event_count");

                    b.Property<double>("MaxSpeedKmh")
                        .HasColumnType("double precision")
                        .HasColumnName("max_speed_kmh");

                    b.Property<double>("SpeedSum")
                        .HasColumnType("double precision")
                        .HasColumnName("speed_sum");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("EntityType", "EntityId", "BucketHour");

                    b.ToTable("entity_hourly_stats", (string)null);
                });

            modelBuilder.Entity("MovementIntel.Domain.Entities.RawMovementEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Attributes")
                        .HasColumnType("jsonb")
                        .HasColumnName("attributes");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entity_type");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<DateTime>("ReceivedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("received_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Source")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.Property<double?>("SpeedKmh")
                        .HasColumnType("double precision")
                        .HasColumnName("speed_kmh");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamptz")
                        .HasColumnName("timestamp");

                    b.HasKey("EventId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("EntityType", "EntityId", "Timestamp");

                    b.ToTable("raw_movement_events", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
